### ISSUE TITLE
requirements file?

### ISSUE THREAD

**Issue by kaelfischer** [OpenTrons/getting-started#1]
I always feel better when I have the requirements explicitly listed in requirements.txt.

**Comment by andySigler** [comment]
Thank you for the feedback, I've added requirements.txt file even though I'm not sure of a way to install dependencies from this file when running Jupyter. The first tutorial covers installing and updating the Opentrons API through `pip` when running inside Jupyter. I've also included a link to our recommended Jupyter installation method in the README.md
